dist: trusty

language: python
python:
- '3.7'
# - 'nightly'

addons:
    firefox: "49.0"

before_install:
    - sudo apt-get install nodejs

before_script:
  - "export DISPLAY=:99.0"
  - "./transcrypt/development/continuous_integration/run prepare"

script: "./transcrypt/development/continuous_integration/run no_cleanup set1"

